version: '2'

services:

  vector:
    image: allmende/vector:0.7.3
    command: start
    ports:
      - "8080:8080"
    volumes:
      - /srv/matrix/data:/data

  matrix:
    image: allmende/synapse:0.16.1
    command: start
    ports:
      - "8448:8448"
    volumes:
      - /srv/matrix/data:/data

  coturn:
    image: allmende/coturn
    command: start
    expose:
      - "3478"
      - "3479"
      - "5349"
      - "5350"
    ports:
      - "3478:3478/udp"
    volumes:
      - /srv/matrix/data:/data
