version: '2'

services:

  vector:
    image: nic0d/matrix-riot-docker:v0.8.1
    command: start
    ports:
      - "8080:8080"
    volumes:
      - /srv/matrix/data:/data

# Use of collocated matrix + coturn servers
  matrix:
    image: nic0d/docker-matrix:v0.18.1
    command: start
    ports:
      - "8448:8448"
      - "3478:3478/udp"
    expose:
      - "3478"
      - "3479"
      - "5349"
      - "5350"
    volumes:
      - /srv/matrix/data:/data