version: '2'

services:

  vector:
    image: nic0d/matrix-riot-docker:v0.8.1
    command: generate
    volumes:
      - /srv/matrix/data:/data
    environment:
      - SERVER_NAME=localhost

# Use of collocated matrix + coturn servers
  matrix:
    image: nic0d/docker-matrix:debian
    command: generate
    volumes:
      - /srv/matrix/data:/data
    environment:
      - REPORT_STATS=no
      - SERVER_NAME=localhost

